services:
  onlinestore:
    image: ${DOCKER_REGISTRY-}onlinestore
    container_name: onlinestore
    restart: always
    build:
      context: .\OnlineStore.Server
      dockerfile: OnlineStore.Server\Dockerfile
    env_file:
    - .env
    depends_on:
      - db_postgres
    ports:
      - 5000:8080
      - 7000:8081
    networks:
      - store_network

  db_postgres:
    image: elestio/postgres:${SOFTWARE_VERSION_TAG}
    container_name: db_postgres
    restart: always
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ADMIN_NAME}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - store_network

  pgadmin:
    image: elestio/pgadmin:REL-8_12
    container_name: pgadmin
    restart: always
    env_file:
    - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    depends_on:
      - db_postgres
    ports:
      - "${PG_PORT}:8080"
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    networks:
      - store_network

networks:
  store_network:
    driver: bridge

volumes:
  postgres:
  pgadmin: