services:
  onlinestore:
    image: ${DOCKER_REGISTRY-}onlinestore
    container_name: onlinestore
    restart: always
    build:
      context: .\OnlineStore.Server
      dockerfile: OnlineStore.Server\Dockerfile
      args:
        DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
        PUBLIC_KEY: ${PUBLIC_KEY}
        PRIVATE_KEY: ${PRIVATE_KEY}
    depends_on:
      - db_postgres
    ports:
      - 5000:8080
      - 7000:8081
    networks:
      - store_network

  db_postgres:
    image: elestio/postgres:16
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ADMIN_NAME}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - store_network

  pgadmin:
    image: elestio/pgadmin:REL-8_12
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    depends_on:
      - db_postgres
    ports:
      - "${PG_PORT}:8080"
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    networks:
      - store_network

  onlinestore-client:
    build:
      context: ./onlinestore.client/
      dockerfile: Dockerfile
      args:
        VITE_APP_HOST: ${VITE_APP_HOST}
    container_name: onlinestore-client
    restart: unless-stopped
    ports:
      - "5777:80"
    networks:
      - store_network

networks:
  store_network:
    driver: bridge

volumes:
  postgres:
  pgadmin: